import { createServerClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import type { Review } from "@/lib/types";

interface SharePageProps {
  params: Promise<{ reviewId: string }>;
}

export default async function SharePage({ params }: SharePageProps) {
  const { reviewId } = await params;
  const supabase = createServerClient();

  const { data, error } = await supabase
    .from("reviews")
    .select("*")
    .eq("id", reviewId)
    .eq("is_public", true)
    .single();

  if (error || !data) notFound();

  const review = data as Review & {
    pr_title: string;
    repo_full_name: string;
    pr_number: number;
    complexity_score: number | null;
    created_at: string;
  };

  const complexityScore = review.complexity_score;
  const scoreColor =
    complexityScore === null
      ? "bg-slate-100 text-slate-600"
      : complexityScore <= 4
      ? "bg-emerald-100 text-emerald-700"
      : complexityScore <= 7
      ? "bg-yellow-100 text-yellow-700"
      : "bg-red-100 text-red-700";

  return (
    <main className="max-w-3xl mx-auto px-4 py-12">
      <div className="mb-2">
        <span className="text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded-full">
          GitPulse AI Review
        </span>
      </div>

      <h1 className="text-2xl font-bold text-slate-900 mt-4 mb-1">{review.pr_title}</h1>

      <div className="flex items-center gap-4 text-sm text-slate-500 mb-6">
        <span className="font-mono">{review.repo_full_name} · PR #{review.pr_number}</span>
        <span>{new Date(review.created_at).toLocaleDateString()}</span>
        {complexityScore !== null && (
          <span className={`px-2 py-0.5 rounded-full text-xs font-semibold ${scoreColor}`}>
            Complexity {complexityScore}/10
          </span>
        )}
      </div>

      <div className="rounded-xl border border-slate-200 bg-white shadow-sm p-6">
        <pre className="text-sm text-slate-700 whitespace-pre-wrap font-sans leading-relaxed">
          {review.review_text}
        </pre>
      </div>

      <p className="text-center text-xs text-slate-400 mt-8">
        Generated by{" "}
        <a href="/" className="text-blue-500 hover:underline">
          GitPulse
        </a>{" "}
        · AI-powered GitHub PR reviews
      </p>
    </main>
  );
}
